apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flaskd
  name: flaskd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskd
  strategy: {}
  template:
    metadata:
      labels:
        app: flaskd
    spec:
      containers:
      - image: nvrbckdown/flask-app
        name: flask-app
        ports:
        - containerPort: 5000
        resources: {}
status: {}
