apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx2
    project: practice
    author: sardor
  name: nginx2
spec:
  containers:
  - image: nginx
    name: nginx2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
