apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx1
    project: practice
    author: sardor
  name: nginx1
spec:
  containers:
  - image: nginx
    name: nginx1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
